---
- name: create motd
  hosts: all
  become: yes
  tasks:
  - name: create the motd
    template:
      src: files/motd.j2
      dest: /etc/motd
      owner: root
      group: root
      mode: 0644
...

